/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'surbhisharma' at '9/6/16 12:24 PM' with Gradle 2.14
 *
 * @author surbhisharma, @date 9/6/16 12:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
